name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Bump version a
      uses: remorses/bump-version@master
      with:
        version_file: a/VERSION
        prefix: a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version b
      uses: remorses/bump-version@master
      with:
        version_file: b/VERSION
        prefix: a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
