name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: a
    - uses: remorses/bump-version@js
      with:
        version_file: b/VERSION
        prefix: b
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

