name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Get Changed Files
      uses: lots0logs/gh-action-get-changed-files@master
    - run: cat ${HOME}/files.json
    - uses: actions/checkout@v1
    - name: Bump version a
      uses: remorses/bump-version@master
      with:
        version_file: a/VERSION
        prefix: "a"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version b
      uses: remorses/bump-version@master
      # working-directory: b
      with:
        version_file: b/VERSION
        prefix: b
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

